/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Occupancy
 */
public class OccupancyTest {
    private final Occupancy model = new Occupancy();

    /**
     * Model tests for Occupancy
     */
    @Test
    public void testOccupancy() {
        // TODO: test Occupancy
    }

    /**
     * Test the property 'presenceConnections'
     */
    @Test
    public void presenceConnectionsTest() {
        // TODO: test presenceConnections
    }

    /**
     * Test the property 'presenceMembers'
     */
    @Test
    public void presenceMembersTest() {
        // TODO: test presenceMembers
    }

    /**
     * Test the property 'presenceSubscribers'
     */
    @Test
    public void presenceSubscribersTest() {
        // TODO: test presenceSubscribers
    }

    /**
     * Test the property 'publishers'
     */
    @Test
    public void publishersTest() {
        // TODO: test publishers
    }

    /**
     * Test the property 'subscribers'
     */
    @Test
    public void subscribersTest() {
        // TODO: test subscribers
    }

}
