/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Push;
import com.konfigthis.client.model.Recipient;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublishPushNotificationToDevicesRequest
 */
public class PublishPushNotificationToDevicesRequestTest {
    private final PublishPushNotificationToDevicesRequest model = new PublishPushNotificationToDevicesRequest();

    /**
     * Model tests for PublishPushNotificationToDevicesRequest
     */
    @Test
    public void testPublishPushNotificationToDevicesRequest() {
        // TODO: test PublishPushNotificationToDevicesRequest
    }

    /**
     * Test the property 'push'
     */
    @Test
    public void pushTest() {
        // TODO: test push
    }

    /**
     * Test the property 'recipient'
     */
    @Test
    public void recipientTest() {
        // TODO: test recipient
    }

}
