/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Notification;
import com.konfigthis.client.model.PushApns;
import com.konfigthis.client.model.PushFcm;
import com.konfigthis.client.model.PushWeb;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Push
 */
public class PushTest {
    private final Push model = new Push();

    /**
     * Model tests for Push
     */
    @Test
    public void testPush() {
        // TODO: test Push
    }

    /**
     * Test the property 'apns'
     */
    @Test
    public void apnsTest() {
        // TODO: test apns
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'fcm'
     */
    @Test
    public void fcmTest() {
        // TODO: test fcm
    }

    /**
     * Test the property 'notification'
     */
    @Test
    public void notificationTest() {
        // TODO: test notification
    }

    /**
     * Test the property 'web'
     */
    @Test
    public void webTest() {
        // TODO: test web
    }

}
