/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Recipient
 */
public class RecipientTest {
    private final Recipient model = new Recipient();

    /**
     * Model tests for Recipient
     */
    @Test
    public void testRecipient() {
        // TODO: test Recipient
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'deviceId'
     */
    @Test
    public void deviceIdTest() {
        // TODO: test deviceId
    }

    /**
     * Test the property 'deviceToken'
     */
    @Test
    public void deviceTokenTest() {
        // TODO: test deviceToken
    }

    /**
     * Test the property 'registrationToken'
     */
    @Test
    public void registrationTokenTest() {
        // TODO: test registrationToken
    }

    /**
     * Test the property 'transportType'
     */
    @Test
    public void transportTypeTest() {
        // TODO: test transportType
    }

}
