/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SignedTokenRequestAllOf
 */
public class SignedTokenRequestAllOfTest {
    private final SignedTokenRequestAllOf model = new SignedTokenRequestAllOf();

    /**
     * Model tests for SignedTokenRequestAllOf
     */
    @Test
    public void testSignedTokenRequestAllOf() {
        // TODO: test SignedTokenRequestAllOf
    }

    /**
     * Test the property 'mac'
     */
    @Test
    public void macTest() {
        // TODO: test mac
    }

}
