/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HistoryApi
 */
@Disabled
public class HistoryApiTest {

    private static HistoryApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new HistoryApi(apiClient);
    }

    /**
     * Get message history for a channel
     *
     * Get message history for a channel
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMessagesByChannelTest() throws ApiException {
        String channelId = null;
        String xAblyVersion = null;
        String format = null;
        String start = null;
        Integer limit = null;
        String end = null;
        String direction = null;
        List<Message> response = api.getMessagesByChannel(channelId)
                .xAblyVersion(xAblyVersion)
                .format(format)
                .start(start)
                .limit(limit)
                .end(end)
                .direction(direction)
                .execute();
        // TODO: test validations
    }

    /**
     * Get presence history of a channel
     *
     * Get presence on a channel
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPresenceHistoryOfChannelTest() throws ApiException {
        String channelId = null;
        String xAblyVersion = null;
        String format = null;
        String start = null;
        Integer limit = null;
        String end = null;
        String direction = null;
        List<PresenceMessage> response = api.getPresenceHistoryOfChannel(channelId)
                .xAblyVersion(xAblyVersion)
                .format(format)
                .start(start)
                .limit(limit)
                .end(end)
                .direction(direction)
                .execute();
        // TODO: test validations
    }

}
