/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Error;
import com.konfigthis.client.model.Extras;
import com.konfigthis.client.model.Message;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublishingApi
 */
@Disabled
public class PublishingApiTest {

    private static PublishingApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PublishingApi(apiClient);
    }

    /**
     * Publish a message to a channel
     *
     * Publish a message to the specified channel
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void publishMessagesToChannelTest() throws ApiException {
        String channelId = null;
        String clientId = null;
        String connectionId = null;
        String data = null;
        String encoding = null;
        Extras extras = null;
        String id = null;
        String name = null;
        Long timestamp = null;
        String xAblyVersion = null;
        String format = null;
        PublishMessagesToChannel2XXResponse response = api.publishMessagesToChannel(channelId)
                .clientId(clientId)
                .connectionId(connectionId)
                .data(data)
                .encoding(encoding)
                .extras(extras)
                .id(id)
                .name(name)
                .timestamp(timestamp)
                .xAblyVersion(xAblyVersion)
                .format(format)
                .execute();
        // TODO: test validations
    }

}
