/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatsApi
 */
@Disabled
public class StatsApiTest {

    private static StatsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new StatsApi(apiClient);
    }

    /**
     * Retrieve usage statistics for an application
     *
     * The Ably system can be queried to obtain usage statistics for a given application, and results are provided aggregated across all channels in use in the application in the specified period. Stats may be used to track usage against account quotas.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getStatsTest() throws ApiException {
        String xAblyVersion = null;
        String format = null;
        String start = null;
        Integer limit = null;
        String end = null;
        String direction = null;
        String unit = null;
        Object response = api.getStats()
                .xAblyVersion(xAblyVersion)
                .format(format)
                .start(start)
                .limit(limit)
                .end(end)
                .direction(direction)
                .unit(unit)
                .execute();
        // TODO: test validations
    }

    /**
     * Get the service time
     *
     * This returns the service time in milliseconds since the epoch.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTimeTest() throws ApiException {
        String xAblyVersion = null;
        String format = null;
        List<Integer> response = api.getTime()
                .xAblyVersion(xAblyVersion)
                .format(format)
                .execute();
        // TODO: test validations
    }

}
