/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ChannelDetails;
import com.konfigthis.client.model.Error;
import com.konfigthis.client.model.PresenceMessage;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatusApi
 */
@Disabled
public class StatusApiTest {

    private static StatusApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new StatusApi(apiClient);
    }

    /**
     * Enumerate all active channels of the application
     *
     * Enumerate all active channels of the application
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMetadataOfAllChannelsTest() throws ApiException {
        String xAblyVersion = null;
        String format = null;
        Integer limit = null;
        String prefix = null;
        String by = null;
        Object response = api.getMetadataOfAllChannels()
                .xAblyVersion(xAblyVersion)
                .format(format)
                .limit(limit)
                .prefix(prefix)
                .by(by)
                .execute();
        // TODO: test validations
    }

    /**
     * Get metadata of a channel
     *
     * Get metadata of a channel
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMetadataOfChannelTest() throws ApiException {
        String channelId = null;
        String xAblyVersion = null;
        String format = null;
        ChannelDetails response = api.getMetadataOfChannel(channelId)
                .xAblyVersion(xAblyVersion)
                .format(format)
                .execute();
        // TODO: test validations
    }

    /**
     * Get presence of a channel
     *
     * Get presence on a channel
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPresenceOfChannelTest() throws ApiException {
        String channelId = null;
        String xAblyVersion = null;
        String format = null;
        String clientId = null;
        String connectionId = null;
        Integer limit = null;
        List<PresenceMessage> response = api.getPresenceOfChannel(channelId)
                .xAblyVersion(xAblyVersion)
                .format(format)
                .clientId(clientId)
                .connectionId(connectionId)
                .limit(limit)
                .execute();
        // TODO: test validations
    }

}
