/*
 * Platform API
 * The [REST API specification](https://www.ably.io/documentation/rest-api) for Ably.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@ably.io
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.ChannelDetails;
import com.konfigthis.client.model.Error;
import com.konfigthis.client.model.PresenceMessage;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class StatusApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public StatusApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public StatusApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getMetadataOfAllChannelsCall(String xAblyVersion, String format, Integer limit, String prefix, String by, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/channels";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (format != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("format", format));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (prefix != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("prefix", prefix));
        }

        if (by != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("by", by));
        }

        if (xAblyVersion != null) {
            localVarHeaderParams.put("X-Ably-Version", localVarApiClient.parameterToString(xAblyVersion));
        }

        final String[] localVarAccepts = {
            "application/json",
            "application/x-msgpack",
            "text/html"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMetadataOfAllChannelsValidateBeforeCall(String xAblyVersion, String format, Integer limit, String prefix, String by, final ApiCallback _callback) throws ApiException {
        return getMetadataOfAllChannelsCall(xAblyVersion, format, limit, prefix, by, _callback);

    }


    private ApiResponse<Object> getMetadataOfAllChannelsWithHttpInfo(String xAblyVersion, String format, Integer limit, String prefix, String by) throws ApiException {
        okhttp3.Call localVarCall = getMetadataOfAllChannelsValidateBeforeCall(xAblyVersion, format, limit, prefix, by, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getMetadataOfAllChannelsAsync(String xAblyVersion, String format, Integer limit, String prefix, String by, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMetadataOfAllChannelsValidateBeforeCall(xAblyVersion, format, limit, prefix, by, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetMetadataOfAllChannelsRequestBuilder {
        private String xAblyVersion;
        private String format;
        private Integer limit;
        private String prefix;
        private String by;

        private GetMetadataOfAllChannelsRequestBuilder() {
        }

        /**
         * Set xAblyVersion
         * @param xAblyVersion The version of the API you wish to use. (optional)
         * @return GetMetadataOfAllChannelsRequestBuilder
         */
        public GetMetadataOfAllChannelsRequestBuilder xAblyVersion(String xAblyVersion) {
            this.xAblyVersion = xAblyVersion;
            return this;
        }
        
        /**
         * Set format
         * @param format The response format you would like (optional)
         * @return GetMetadataOfAllChannelsRequestBuilder
         */
        public GetMetadataOfAllChannelsRequestBuilder format(String format) {
            this.format = format;
            return this;
        }
        
        /**
         * Set limit
         * @param limit  (optional, default to 100)
         * @return GetMetadataOfAllChannelsRequestBuilder
         */
        public GetMetadataOfAllChannelsRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Set prefix
         * @param prefix Optionally limits the query to only those channels whose name starts with the given prefix (optional)
         * @return GetMetadataOfAllChannelsRequestBuilder
         */
        public GetMetadataOfAllChannelsRequestBuilder prefix(String prefix) {
            this.prefix = prefix;
            return this;
        }
        
        /**
         * Set by
         * @param by optionally specifies whether to return just channel names (by&#x3D;id) or ChannelDetails (by&#x3D;value) (optional)
         * @return GetMetadataOfAllChannelsRequestBuilder
         */
        public GetMetadataOfAllChannelsRequestBuilder by(String by) {
            this.by = by;
            return this;
        }
        
        /**
         * Build call for getMetadataOfAllChannels
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getMetadataOfAllChannelsCall(xAblyVersion, format, limit, prefix, by, _callback);
        }


        /**
         * Execute getMetadataOfAllChannels request
         * @return Object
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public Object execute() throws ApiException {
            ApiResponse<Object> localVarResp = getMetadataOfAllChannelsWithHttpInfo(xAblyVersion, format, limit, prefix, by);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getMetadataOfAllChannels request with HTTP info returned
         * @return ApiResponse&lt;Object&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public ApiResponse<Object> executeWithHttpInfo() throws ApiException {
            return getMetadataOfAllChannelsWithHttpInfo(xAblyVersion, format, limit, prefix, by);
        }

        /**
         * Execute getMetadataOfAllChannels request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Object> _callback) throws ApiException {
            return getMetadataOfAllChannelsAsync(xAblyVersion, format, limit, prefix, by, _callback);
        }
    }

    /**
     * Enumerate all active channels of the application
     * Enumerate all active channels of the application
     * @return GetMetadataOfAllChannelsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
     </table>
     */
    public GetMetadataOfAllChannelsRequestBuilder getMetadataOfAllChannels() throws IllegalArgumentException {
        return new GetMetadataOfAllChannelsRequestBuilder();
    }
    private okhttp3.Call getMetadataOfChannelCall(String channelId, String xAblyVersion, String format, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/channels/{channel_id}"
            .replace("{" + "channel_id" + "}", localVarApiClient.escapeString(channelId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (format != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("format", format));
        }

        if (xAblyVersion != null) {
            localVarHeaderParams.put("X-Ably-Version", localVarApiClient.parameterToString(xAblyVersion));
        }

        final String[] localVarAccepts = {
            "application/json",
            "application/x-msgpack",
            "text/html"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getMetadataOfChannelValidateBeforeCall(String channelId, String xAblyVersion, String format, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'channelId' is set
        if (channelId == null) {
            throw new ApiException("Missing the required parameter 'channelId' when calling getMetadataOfChannel(Async)");
        }

        return getMetadataOfChannelCall(channelId, xAblyVersion, format, _callback);

    }


    private ApiResponse<ChannelDetails> getMetadataOfChannelWithHttpInfo(String channelId, String xAblyVersion, String format) throws ApiException {
        okhttp3.Call localVarCall = getMetadataOfChannelValidateBeforeCall(channelId, xAblyVersion, format, null);
        Type localVarReturnType = new TypeToken<ChannelDetails>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getMetadataOfChannelAsync(String channelId, String xAblyVersion, String format, final ApiCallback<ChannelDetails> _callback) throws ApiException {

        okhttp3.Call localVarCall = getMetadataOfChannelValidateBeforeCall(channelId, xAblyVersion, format, _callback);
        Type localVarReturnType = new TypeToken<ChannelDetails>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetMetadataOfChannelRequestBuilder {
        private final String channelId;
        private String xAblyVersion;
        private String format;

        private GetMetadataOfChannelRequestBuilder(String channelId) {
            this.channelId = channelId;
        }

        /**
         * Set xAblyVersion
         * @param xAblyVersion The version of the API you wish to use. (optional)
         * @return GetMetadataOfChannelRequestBuilder
         */
        public GetMetadataOfChannelRequestBuilder xAblyVersion(String xAblyVersion) {
            this.xAblyVersion = xAblyVersion;
            return this;
        }
        
        /**
         * Set format
         * @param format The response format you would like (optional)
         * @return GetMetadataOfChannelRequestBuilder
         */
        public GetMetadataOfChannelRequestBuilder format(String format) {
            this.format = format;
            return this;
        }
        
        /**
         * Build call for getMetadataOfChannel
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getMetadataOfChannelCall(channelId, xAblyVersion, format, _callback);
        }


        /**
         * Execute getMetadataOfChannel request
         * @return ChannelDetails
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public ChannelDetails execute() throws ApiException {
            ApiResponse<ChannelDetails> localVarResp = getMetadataOfChannelWithHttpInfo(channelId, xAblyVersion, format);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getMetadataOfChannel request with HTTP info returned
         * @return ApiResponse&lt;ChannelDetails&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public ApiResponse<ChannelDetails> executeWithHttpInfo() throws ApiException {
            return getMetadataOfChannelWithHttpInfo(channelId, xAblyVersion, format);
        }

        /**
         * Execute getMetadataOfChannel request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<ChannelDetails> _callback) throws ApiException {
            return getMetadataOfChannelAsync(channelId, xAblyVersion, format, _callback);
        }
    }

    /**
     * Get metadata of a channel
     * Get metadata of a channel
     * @param channelId The [Channel&#39;s ID](https://www.ably.io/documentation/rest/channels). (required)
     * @return GetMetadataOfChannelRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * x-ably-serverid -  <br>  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
     </table>
     */
    public GetMetadataOfChannelRequestBuilder getMetadataOfChannel(String channelId) throws IllegalArgumentException {
        if (channelId == null) throw new IllegalArgumentException("\"channelId\" is required but got null");
            

        return new GetMetadataOfChannelRequestBuilder(channelId);
    }
    private okhttp3.Call getPresenceOfChannelCall(String channelId, String xAblyVersion, String format, String clientId, String connectionId, Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/channels/{channel_id}/presence"
            .replace("{" + "channel_id" + "}", localVarApiClient.escapeString(channelId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (format != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("format", format));
        }

        if (clientId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("clientId", clientId));
        }

        if (connectionId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("connectionId", connectionId));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (xAblyVersion != null) {
            localVarHeaderParams.put("X-Ably-Version", localVarApiClient.parameterToString(xAblyVersion));
        }

        final String[] localVarAccepts = {
            "application/json",
            "application/x-msgpack",
            "text/html"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPresenceOfChannelValidateBeforeCall(String channelId, String xAblyVersion, String format, String clientId, String connectionId, Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'channelId' is set
        if (channelId == null) {
            throw new ApiException("Missing the required parameter 'channelId' when calling getPresenceOfChannel(Async)");
        }

        return getPresenceOfChannelCall(channelId, xAblyVersion, format, clientId, connectionId, limit, _callback);

    }


    private ApiResponse<List<PresenceMessage>> getPresenceOfChannelWithHttpInfo(String channelId, String xAblyVersion, String format, String clientId, String connectionId, Integer limit) throws ApiException {
        okhttp3.Call localVarCall = getPresenceOfChannelValidateBeforeCall(channelId, xAblyVersion, format, clientId, connectionId, limit, null);
        Type localVarReturnType = new TypeToken<List<PresenceMessage>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getPresenceOfChannelAsync(String channelId, String xAblyVersion, String format, String clientId, String connectionId, Integer limit, final ApiCallback<List<PresenceMessage>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPresenceOfChannelValidateBeforeCall(channelId, xAblyVersion, format, clientId, connectionId, limit, _callback);
        Type localVarReturnType = new TypeToken<List<PresenceMessage>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetPresenceOfChannelRequestBuilder {
        private final String channelId;
        private String xAblyVersion;
        private String format;
        private String clientId;
        private String connectionId;
        private Integer limit;

        private GetPresenceOfChannelRequestBuilder(String channelId) {
            this.channelId = channelId;
        }

        /**
         * Set xAblyVersion
         * @param xAblyVersion The version of the API you wish to use. (optional)
         * @return GetPresenceOfChannelRequestBuilder
         */
        public GetPresenceOfChannelRequestBuilder xAblyVersion(String xAblyVersion) {
            this.xAblyVersion = xAblyVersion;
            return this;
        }
        
        /**
         * Set format
         * @param format The response format you would like (optional)
         * @return GetPresenceOfChannelRequestBuilder
         */
        public GetPresenceOfChannelRequestBuilder format(String format) {
            this.format = format;
            return this;
        }
        
        /**
         * Set clientId
         * @param clientId  (optional)
         * @return GetPresenceOfChannelRequestBuilder
         */
        public GetPresenceOfChannelRequestBuilder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }
        
        /**
         * Set connectionId
         * @param connectionId  (optional)
         * @return GetPresenceOfChannelRequestBuilder
         */
        public GetPresenceOfChannelRequestBuilder connectionId(String connectionId) {
            this.connectionId = connectionId;
            return this;
        }
        
        /**
         * Set limit
         * @param limit  (optional, default to 100)
         * @return GetPresenceOfChannelRequestBuilder
         */
        public GetPresenceOfChannelRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Build call for getPresenceOfChannel
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * link -  <br>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getPresenceOfChannelCall(channelId, xAblyVersion, format, clientId, connectionId, limit, _callback);
        }


        /**
         * Execute getPresenceOfChannel request
         * @return List&lt;PresenceMessage&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * link -  <br>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public List<PresenceMessage> execute() throws ApiException {
            ApiResponse<List<PresenceMessage>> localVarResp = getPresenceOfChannelWithHttpInfo(channelId, xAblyVersion, format, clientId, connectionId, limit);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getPresenceOfChannel request with HTTP info returned
         * @return ApiResponse&lt;List&lt;PresenceMessage&gt;&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * link -  <br>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public ApiResponse<List<PresenceMessage>> executeWithHttpInfo() throws ApiException {
            return getPresenceOfChannelWithHttpInfo(channelId, xAblyVersion, format, clientId, connectionId, limit);
        }

        /**
         * Execute getPresenceOfChannel request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> OK </td><td>  * link -  <br>  * x-ably-serverid -  <br>  </td></tr>
            <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<List<PresenceMessage>> _callback) throws ApiException {
            return getPresenceOfChannelAsync(channelId, xAblyVersion, format, clientId, connectionId, limit, _callback);
        }
    }

    /**
     * Get presence of a channel
     * Get presence on a channel
     * @param channelId The [Channel&#39;s ID](https://www.ably.io/documentation/rest/channels). (required)
     * @return GetPresenceOfChannelRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * link -  <br>  * x-ably-serverid -  <br>  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  * x-ably-errorcode -  <br>  * x-ably-errormessage -  <br>  * x-ably-serverid -  <br>  </td></tr>
     </table>
     */
    public GetPresenceOfChannelRequestBuilder getPresenceOfChannel(String channelId) throws IllegalArgumentException {
        if (channelId == null) throw new IllegalArgumentException("\"channelId\" is required but got null");
            

        return new GetPresenceOfChannelRequestBuilder(channelId);
    }
}
